#!/bin/sh
eval `dbus export serverchan_`
url=`echo https://sc.ftqq.com/"$serverchan_sckey".send`
ifup_txt=/tmp/serverchan_ifup.md
reboot_time=$(date "+%Y-%m-%d %H:%M:%S")
sys_uptime=`ubus call system info | jq .uptime|awk '{print int($1/86400)"天 "int($1%86400/3600)"小时 "int(($1%3600)/60)"分钟 "int($1%60)"秒"}'`
j=0
interface_nu=`ubus call network.interface dump|jq '.interface|length'`
date_now=`date +%s`
sys_up_second=`ubus call system info | jq .uptime`
sys_boot_seconds=`expr $date_now - $sys_up_second`
sys_boot_date=`date -d @"$sys_boot_seconds" "+%Y-%m-%d %H:%M:%S"`

echo "##### ** 你的网络刚刚发生了重启，重启后WAN信息如下： **" > $ifup_txt
echo "##### 系统开机时间：$sys_boot_date" >> $ifup_txt
echo "##### 网络重启时间：$reboot_time" >> $ifup_txt
echo "---" >> $ifup_txt

if [ -z "$interface_nu" ];then
	echo "#### ** wan状态：**" >> $ifup_txt
	echo "##### 未找到wan，可能你的wan名字未识别到。" >> $ifup_txt
else
	until [ "$j" == "$interface_nu" ]
	do
		lan_addr_prefix=`uci -q get network.lan.ipaddr|cut -d . -f1,2,3`
		WAN_EXIST=`ubus call network.interface dump|jq .interface[$j]|grep nexthop|grep -v "$lan_addr_prefix."|grep -v 127.0.0.1|sed 's/"nexthop"://g'|grep -v :`
		if [ -n "$WAN_EXIST" ];then
			wan_name=`ubus call network.interface dump|jq .interface[$j].interface|sed 's/"//g'`
			#wan_ifname=`ubus call network.interface dump|jq .interface[$j].device|sed 's/"//g'`
			wan_ifname=`uci -q get network.wan.ifname`
			wan_up=`ubus call network.interface dump|jq .interface[$j].up|sed 's/"//g'`
			wan_ipaddr=`ubus call network.interface.$wan_name status|jq '."ipv4-address"[0].address'|sed 's/"//g'`
			wan_uptime=`ubus call network.interface.$wan_name status|jq .uptime|awk '{print int($1/86400)"天 "int($1%86400/3600)"小时 "int(($1%3600)/60)"分钟 "int($1%60)"秒"}'`
			wan_rx_bytes=`ubus call network.device status|jq ."$wan_ifname".statistics.rx_bytes`
			wan_tx_bytes=`ubus call network.device status|jq ."$wan_ifname".statistics.tx_bytes`
			wan_rx_gb=`awk 'BEGIN{printf "%.2f\n", '$wan_rx_bytes'/'1000000000'}'`
			wan_tx_gb=`awk 'BEGIN{printf "%.2f\n", '$wan_tx_bytes'/'1000000000'}'`
			#public_ip=`curl --interface $wan_ifname -s whatismyip.akamai.com 2>&1` || "本次未获取到！"
			public_ip=`curl --interface $wan_ifname -s https://ip.ngrok.wang/ 2>&1` || "本次未获取到！"
			
			echo "##### ** $wan_name：**" >> $ifup_txt
			if [ "$wan_up" == "true" ] && [ "$wan_ipaddr" != "null" ];then
				echo "##### $wan_name 公网地址: $public_ip" >> $ifup_txt
				echo "##### $wan_name IP地址: $wan_ipaddr" >> $ifup_txt
				echo "##### $wan_name 连接时间: $wan_uptime" >> $ifup_txt
				echo "##### $wan_name 接收流量: $wan_rx_gb GB" >> $ifup_txt
				echo "##### $wan_name 发送流量: $wan_tx_gb GB" >> $ifup_txt
			else
				echo "##### $wan_name 未启用/连接！" >> $ifup_txt
			fi
			echo "---" >> $ifup_txt
		fi
		j=$(($j+1))
	done
fi

serverchan_send_title="Lede X64 V2.2 网络重启通知："
serverchan_send_content=`cat $ifup_txt`

wget --post-data "text=$serverchan_send_title&desp=$serverchan_send_content" -qO- $url > /dev/null

sleep 1
rm -rf $ifup_txt