#!/bin/sh /etc/rc.common

START=18

start() {
	if [ -f "/etc/fwupdate.tar.gz" ]; then
		mv /etc/fwupdate.tar.gz /tmp/restore.tar.gz
		tar -C / -xzf /tmp/restore.tar.gz >/dev/null 2>&1
		sleep 1
		reboot
	fi
}
