{
    "apps": [
        {
            "build_date": "2018-10-21_18:15:54", 
            "changelog": "", 
            "description": "小巧便携的网盘", 
            "home_url": "Module_webd.asp", 
            "md5": "0caf870c95a3962187745e100ead1794", 
            "name": "webd", 
            "tar_url": "webd/webd.tar.gz", 
            "title": "我的网盘", 
            "version": "0.1"
        }, 
        {
            "build_date": "2017-08-31_14:34:01", 
            "description": "将USB磁盘自动挂载到系统", 
            "home_url": "Module_usbmount.asp", 
            "md5": "1b653aa56517aa80bd394e91ad754e84", 
            "name": "usbmount", 
            "tar_url": "usbmount/usbmount.tar.gz", 
            "title": "USB自动挂载", 
            "version": "1.0"
        }, 
        {
            "build_date": "2017-10-25_10:49:24", 
            "changelog": "√修复重启防火墙规则可能丢失的BUG", 
            "description": "高安全的企业VPN服务器", 
            "home_url": "Module_ikev1.asp", 
            "md5": "b94276026e7bb06b14729997be280a48", 
            "name": "ikev1", 
            "tar_url": "ikev1/ikev1.tar.gz", 
            "title": "IPsec服务器", 
            "version": "0.9"
        }, 
        {
            "build_date": "2018-04-26_13:50:07", 
            "changelog": "", 
            "description": "增强路由NAT能力", 
            "home_url": "Module_hwnat.asp", 
            "md5": "3ed528254b38c482f85bbdc2bf32f9f7", 
            "name": "hwnat", 
            "tar_url": "hwnat/hwnat.tar.gz", 
            "title": "NAT硬件加速", 
            "version": "0.1"
        }, 
        {
            "build_date": "2017-10-09_22:23:58", 
            "changelog": "", 
            "description": "增强路由NAT能力", 
            "home_url": "Module_sfe.asp", 
            "md5": "e2b8501f3b232ccd1a9ea0e83537d6a2", 
            "name": "sfe", 
            "tar_url": "sfe/sfe.tar.gz", 
            "title": "SFE快速转发引擎", 
            "version": "0.2"
        }, 
        {
            "build_date": "2019-04-02_21:15:11", 
            "changelog": "修复mac控制", 
            "description": "外服游戏解决方案", 
            "home_url": "Module_sgame.asp", 
            "md5": "ab7432a96012d6eec7b297a45e780150", 
            "name": "sgame", 
            "tar_url": "sgame/sgame.tar.gz", 
            "title": "游戏加速器", 
            "version": "0.8.8"
        }, 
        {
            "build_date": "2017-10-19_20:43:20", 
            "changelog": "", 
            "description": "安装盘剩余空间挂载", 
            "home_url": "Module_kdisk.asp", 
            "md5": "4a48bfb02f098af70635df78df6004de", 
            "name": "kdisk", 
            "tar_url": "kdisk/kdisk.tar.gz", 
            "title": "硬盘助手", 
            "version": "0.2"
        }, 
        {
            "build_date": "2017-10-19_16:08:11", 
            "changelog": "修复新固件下客户端上线通知失效", 
            "description": "推送路由器信息到微信~", 
            "home_url": "Module_serverchan.asp", 
            "md5": "3d0636c351498feb0a0e31cef780bcff", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "Server酱", 
            "version": "1.1.6"
        }, 
        {
            "build_date": "2019-03-09_21:53:00", 
            "changelog": "支持2.30", 
            "description": "超酷的远程下载工具", 
            "home_url": "Module_aria2.asp", 
            "md5": "4613c1bcec6a85fc07a636f15b035b0c", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "Aria2", 
            "version": "2.4"
        }, 
        {
            "build_date": "2019-03-05_13:01:00", 
            "changelog": "增加客户端分流", 
            "description": "多运营商自动分流", 
            "home_url": "Module_policy.asp", 
            "md5": "d745cc09f4a02dd2cc33055ff131a609", 
            "name": "policy", 
            "tar_url": "policy/policy.tar.gz", 
            "title": "策略路由", 
            "version": "0.7"
        }, 
        {
            "build_date": "2019-09-11_12:15:05", 
            "changelog": "安装目录自定义", 
            "description": "Debian系统和Unifi控制器", 
            "home_url": "Module_unifi.asp", 
            "md5": "3f64824dc26ec1155740d9fcbb6223c3", 
            "name": "unifi", 
            "tar_url": "unifi/unifi.tar.gz", 
            "title": "Unifi Controller", 
            "version": "1.0"
        }, 
        {
            "build_date": "2019-01-01_23:37:39", 
            "changelog": "修复2.26默认主题汉化问题", 
            "description": "快速修复当前固件中的BUG", 
            "home_url": "Module_hotfix.asp", 
            "md5": "6e03bc4a9ae7434f7aa711882c8361c6", 
            "name": "hotfix", 
            "tar_url": "hotfix/hotfix.tar.gz", 
            "title": "HOTFIX", 
            "version": "0.2.4"
        }, 
        {
            "build_date": "2019-02-12_22:47:25", 
            "changelog": "更新版本到3.6.4", 
            "description": "百度网盘同步管理工具", 
            "home_url": "Module_baidupcs.asp", 
            "md5": "be01e1fc4c1abb071282d9a151720ee0", 
            "name": "baidupcs", 
            "tar_url": "baidupcs/baidupcs.tar.gz", 
            "title": "百度网盘", 
            "version": "0.2"
        }, 
        {
            "build_date": "2019-03-06_17:29:06", 
            "changelog": "", 
            "description": "在指定时间唤醒设备", 
            "home_url": "Module_timewol.asp", 
            "md5": "931ef3de97eb255cf0fed4b1f4bce4cc", 
            "name": "timewol", 
            "tar_url": "timewol/timewol.tar.gz", 
            "title": "定时唤醒", 
            "version": "0.1"
        }, 
        {
            "build_date": "2018-01-02_11:28:12", 
            "changelog": "修复导致开机网卡无法加载的问题", 
            "description": "拨号到指定号段", 
            "home_url": "Module_pppoeai.asp", 
            "md5": "64dfe3287d4b6d0c9dfa492caab986d1", 
            "name": "pppoeai", 
            "tar_url": "pppoeai/pppoeai.tar.gz", 
            "title": "拨号助手", 
            "version": "1.1"
        }, 
        {
            "build_date": "2017-10-12_11:02:55", 
            "changelog": "", 
            "description": "稳定高效的共享磁盘", 
            "home_url": "Module_iscsi.asp", 
            "md5": "bce7398c37f6797ca4fcf6c874490df6", 
            "name": "iscsi", 
            "tar_url": "iscsi/iscsi.tar.gz", 
            "title": "iSCSI服务器", 
            "version": "0.5"
        }, 
        {
            "build_date": "2017-10-16_19:22:00", 
            "changelog": "", 
            "description": "分布式的虚拟以太网", 
            "home_url": "Module_zerotier.asp", 
            "md5": "d97d8271a7da1cfd4ff813aae8d9b2b9", 
            "name": "zerotier", 
            "tar_url": "zerotier/zerotier.tar.gz", 
            "title": "ZeroTier", 
            "version": "0.1"
        }, 
        {
            "build_date": "2020-02-06_20:54:40", 
            "changelog": "更新二进制版本", 
            "description": "强大易用的全平台同步工具,支持双向同步！", 
            "home_url": "Module_easyexplorer.asp", 
            "md5": "1a91079623d65827a780430c9f2c1ae7", 
            "name": "easyexplorer", 
            "tar_url": "easyexplorer/easyexplorer.tar.gz", 
            "title": "易有云 - EasyExplorer", 
            "version": "1.8"
        }, 
        {
            "build_date": "2017-10-12_15:18:30", 
            "changelog": "", 
            "description": "小巧安全的FTP服务器", 
            "home_url": "Module_ftp.asp", 
            "md5": "4dcc993dd617ed88a3db1938aad0aa06", 
            "name": "ftp", 
            "tar_url": "ftp/ftp.tar.gz", 
            "title": "FTP服务器", 
            "version": "1.0.4"
        }, 
        {
            "build_date": "2018-05-12_14:47:04", 
            "changelog": "增加断线重拨自动重置", 
            "description": "宽带上下行提速", 
            "home_url": "Module_fastdick.asp", 
            "md5": "c02bb56eddbc0ccd7996753e9bdcd099", 
            "name": "fastdick", 
            "tar_url": "fastdick/fastdick.tar.gz", 
            "title": "迅雷快鸟", 
            "version": "0.9"
        }, 
        {
            "build_date": "2018-04-17_14:54:36", 
            "changelog": "修复ali，cloudxns接口", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "8dae2c9a1c2145667586d2fc6da9cb65", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "0.5"
        }, 
        {
            "build_date": "2018-10-19_21:00:25", 
            "changelog": "启用后关闭一些功能", 
            "description": "无感知的透明防火墙", 
            "home_url": "Module_bridge.asp", 
            "md5": "46550f4385a70832030d7b9a69ce159d", 
            "name": "bridge", 
            "tar_url": "bridge/bridge.tar.gz", 
            "title": "透明网桥", 
            "version": "0.2"
        }, 
        {
            "build_date": "2019-02-12_22:32:00", 
            "changelog": "修复创建容器的错误", 
            "description": "轻量虚拟化应用程序", 
            "home_url": "Module_docker.asp", 
            "md5": "1db81c9a93ff2f4a7d6cc1d657c57eec", 
            "name": "docker", 
            "tar_url": "docker/docker.tar.gz", 
            "title": "Docker", 
            "version": "0.2.3"
        }, 
        {
            "build_date": "2018-11-14_15:31:06", 
            "changelog": "升级bin到2018-10-20", 
            "description": "巨硬套餐激活工具", 
            "home_url": "Module_kms.asp", 
            "md5": "b5fe5e2d99ae4694a7d3c1a3e42c8c7b", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "KMS", 
            "version": "0.9"
        }, 
        {
            "build_date": "2017-11-24_18:16:42", 
            "changelog": "", 
            "description": "PPPOE服务器", 
            "home_url": "Module_pppoeserver.asp", 
            "md5": "b544bc87f2450e7de5cfcffb891c3f0b", 
            "name": "pppoeserver", 
            "tar_url": "pppoeserver/pppoeserver.tar.gz", 
            "title": "PPPoE Server", 
            "version": "0.1"
        }, 
        {
            "build_date": "2019-03-09_15:14:20", 
            "changelog": "修改bbrplus模块名称", 
            "description": "魔改BBR", 
            "home_url": "Module_bbr.asp", 
            "md5": "c3c59f621e7577e3cc645a88c9e65583", 
            "name": "bbr", 
            "tar_url": "bbr/bbr.tar.gz", 
            "title": "BBR MOD", 
            "version": "0.4"
        }, 
        {
            "build_date": "2017-10-01_16:30:07", 
            "changelog": "", 
            "description": "内存管理小助手", 
            "home_url": "Module_memory.asp", 
            "md5": "5c32304458a48423e79d042cdef50c84", 
            "name": "memory", 
            "tar_url": "memory/memory.tar.gz", 
            "title": "内存管理", 
            "version": "0.2"
        }, 
        {
            "build_date": "2019-03-28_12:47:23", 
            "changelog": "修复读取cookie错误", 
            "description": "每日批量自动签到", 
            "home_url": "Module_autocheckin.asp", 
            "md5": "b412b6742fd02e0d9f50ba84a7d1d036", 
            "name": "autocheckin", 
            "tar_url": "autocheckin/autocheckin.tar.gz", 
            "title": "签到狗2.0", 
            "version": "1.2"
        }, 
        {
            "build_date": "2019-03-02_16:54:35", 
            "changelog": "优化接口获取", 
            "description": "系统路由表设置", 
            "home_url": "Module_routetable.asp", 
            "md5": "9ba11c2a485883017f0efe0c1073dd36", 
            "name": "routetable", 
            "tar_url": "routetable/routetable.tar.gz", 
            "title": "路由表", 
            "version": "0.7"
        }, 
        {
            "build_date": "2017-10-03_00:51:16", 
            "changelog": "", 
            "description": "小巧便携BT下载器", 
            "home_url": "Module_cloud_torrent.asp", 
            "md5": "24e4769a0a69ad1d609cae1af1644077", 
            "name": "cloud_torrent", 
            "tar_url": "cloud_torrent/cloud_torrent.tar.gz", 
            "title": "cloud torrent", 
            "version": "1.6"
        }, 
        {
            "build_date": "2017-10-14_15:22:41", 
            "changelog": "", 
            "description": "仪表式查看路由详细状态", 
            "home_url": "Module_netdata.asp", 
            "md5": "3e5c0915964b29af4cd31cffe145c71a", 
            "name": "netdata", 
            "tar_url": "netdata/netdata.tar.gz", 
            "title": "路由监控", 
            "version": "0.1"
        }, 
        {
            "build_date": "2018-08-05_14:03:00", 
            "changelog": "", 
            "description": "每日批量自动签到", 
            "home_url": "Module_smzdm.asp", 
            "md5": "3ae7e044052c18c62bbe2ad5cb9166a8", 
            "name": "smzdm", 
            "tar_url": "smzdm/smzdm.tar.gz", 
            "title": "什么值得买", 
            "version": "0.1"
        }, 
        {
            "build_date": "2019-03-01_01:21:54", 
            "changelog": "", 
            "description": "端口映射、中转流量", 
            "home_url": "Module_relay.asp", 
            "md5": "c8ca3f8d4d0e5d2cfef5481012018108", 
            "name": "relay", 
            "tar_url": "relay/relay.tar.gz", 
            "title": "瑞士军刀", 
            "version": "0.1"
        }, 
        {
            "build_date": "2018-09-29_17:10:04", 
            "changelog": "", 
            "description": "NAT类型-Full cone", 
            "home_url": "Module_nat1.asp", 
            "md5": "51eff74d8d71eced42666902a6c87b19", 
            "name": "nat1", 
            "tar_url": "nat1/nat1.tar.gz", 
            "title": "Full cone NAT", 
            "version": "0.2"
        }, 
        {
            "build_date": "2018-05-28_12:44:39", 
            "changelog": "更新验证方式", 
            "description": "支持http2协议的远程管理，仅支持远程管理路由器+NAS+Windows远程桌面", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "d43d97cc43f39820da66660acca6f6a6", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "DDNSTO 远程穿透", 
            "version": "2.0"
        }, 
        {
            "build_date": "2017-09-19_12:21:44", 
            "changelog": "", 
            "description": "使PPPoE能够跨路由使用", 
            "home_url": "Module_pppoerelay.asp", 
            "md5": "22ba1771273ee9b3248ad73968d5e710", 
            "name": "pppoerelay", 
            "tar_url": "pppoerelay/pppoerelay.tar.gz", 
            "title": "PPPoE Relay", 
            "version": "0.1"
        }, 
        {
            "build_date": "2017-10-03_00:53:49", 
            "changelog": "", 
            "description": "轻松搭建私有云", 
            "home_url": "Module_syncthing.asp", 
            "md5": "933176300150bc2926ba00daf6299b61", 
            "name": "syncthing", 
            "tar_url": "syncthing/syncthing.tar.gz", 
            "title": "syncthing", 
            "version": "1.8"
        }, 
        {
            "build_date": "2019-03-06_17:54:34", 
            "changelog": "", 
            "description": "限时网址及协议过滤", 
            "home_url": "Module_mia.asp", 
            "md5": "a90bada3770bc781084784d19d50b0dd", 
            "name": "mia", 
            "tar_url": "mia/mia.tar.gz", 
            "title": "家长控制", 
            "version": "0.1"
        }, 
        {
            "build_date": "2018-10-18_19:08:26", 
            "changelog": "修复BUG", 
            "description": "小宝开发的游戏加速V2", 
            "home_url": "Module_koolgame.asp", 
            "md5": "de2bac13f13301434a08958cff339fbe", 
            "name": "koolgame", 
            "tar_url": "koolgame/koolgame.tar.gz", 
            "title": "koolgame 游戏加速", 
            "version": "1.0.8"
        }, 
        {
            "build_date": "2019-03-12_12:08:38", 
            "changelog": "支持2.30", 
            "description": "软件中心自动云备份和恢复", 
            "home_url": "Module_cos.asp", 
            "md5": "32116fb4f27c21b369229d7df3afbeca", 
            "name": "cos", 
            "tar_url": "cos/cos.tar.gz", 
            "title": "腾讯云存储", 
            "version": "0.5"
        }, 
        {
            "build_date": "2018-11-11_15:42:40", 
            "changelog": "更新ONMP", 
            "description": "Entware环境和扩展", 
            "home_url": "Module_entware.asp", 
            "md5": "b33613acacda12f8dc30a6efa9f65177", 
            "name": "entware", 
            "tar_url": "entware/entware.tar.gz", 
            "title": "Entware", 
            "version": "0.4"
        }, 
        {
            "build_date": "2017-08-07_23:30:31", 
            "description": "超强的SSH网页客户端", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "030789c4f28c34bafa3a65f16198691b", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "ShellnaBox", 
            "version": "1.1.5"
        }, 
        {
            "build_date": "2017-12-28_15:18:04", 
            "changelog": "修复安装web出错误的问题", 
            "description": "高效的BT、PT下载工具", 
            "home_url": "Module_transmission.asp", 
            "md5": "4e8704d2f4bb117a4ac9d6d4e1008040", 
            "name": "transmission", 
            "tar_url": "transmission/transmission.tar.gz", 
            "title": "Transmission", 
            "version": "0.6"
        }, 
        {
            "build_date": "2019-03-10_11:29:50", 
            "changelog": "", 
            "description": "在线更新路由器固件", 
            "home_url": "Module_fwupdate.asp", 
            "md5": "b42b2d325dcf25573a9546bce6f32740", 
            "name": "fwupdate", 
            "tar_url": "fwupdate/fwupdate.tar.gz", 
            "title": "固件更新", 
            "version": "0.2.7"
        }, 
        {
            "build_date": "2019-01-25_00:21:08", 
            "changelog": "优化安装提示", 
            "description": "与你的网络无缝并行", 
            "home_url": "Module_anyconnect.asp", 
            "md5": "614fb961a0a44bc618cc2dc359fb2c65", 
            "name": "anyconnect", 
            "tar_url": "anyconnect/anyconnect.tar.gz", 
            "title": "AnyConnect Server", 
            "version": "0.9"
        }, 
        {
            "build_date": "2019-03-06_20:57:24", 
            "changelog": "", 
            "description": "查看网址和搜索记录", 
            "home_url": "Module_webrecord.asp", 
            "md5": "81b23b5fa63f404a9b311d8e268d1059", 
            "name": "webrecord", 
            "tar_url": "webrecord/webrecord.tar.gz", 
            "title": "上网记录", 
            "version": "0.1"
        }, 
        {
            "build_date": "2017-12-26_16:07:21", 
            "changelog": "", 
            "description": "开源的P2P加密组网", 
            "home_url": "Module_n2n.asp", 
            "md5": "3a88c76588e7cddd561fecd07670f507", 
            "name": "n2n", 
            "tar_url": "n2n/n2n.tar.gz", 
            "title": "N2N V2", 
            "version": "0.1"
        }, 
        {
            "build_date": "2017-10-12_11:01:40", 
            "changelog": "", 
            "description": "自动化部署WEB环境", 
            "home_url": "Module_lnmp.asp", 
            "md5": "c11f11e5c7389d64b0a445149d79ce60", 
            "name": "lnmp", 
            "tar_url": "lnmp/lnmp.tar.gz", 
            "title": "LNMP", 
            "version": "0.6"
        }, 
        {
            "build_date": "2018-07-01_17:38:34", 
            "changelog": "修复配件无法搜索到的问题", 
            "description": "智能家庭网关", 
            "home_url": "Module_homebridge.asp", 
            "md5": "21fbf23db80e51f1395c93e5e349d0f5", 
            "name": "homebridge", 
            "tar_url": "homebridge/homebridge.tar.gz", 
            "title": "Homebridge", 
            "version": "0.8"
        }, 
        {
            "build_date": "2017-09-09_18:23:16", 
            "description": "将客户端完全暴露在公网", 
            "home_url": "Module_dmz.asp", 
            "md5": "a428eb4ab6054972cfa01d0e34ab5507", 
            "name": "dmz", 
            "tar_url": "dmz/dmz.tar.gz", 
            "title": "DMZ", 
            "version": "0.4"
        }, 
        {
            "build_date": "2018-06-14_21:13:13", 
            "changelog": "增加自定义配置功能", 
            "description": "FRPC内网穿透工具", 
            "home_url": "Module_frpc.asp", 
            "md5": "47b813f9d36a802b73b0a7929f7bf917", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc", 
            "version": "2.1"
        }, 
        {
            "build_date": "2019-03-09_20:57:23", 
            "changelog": "支持2.30", 
            "description": "VPN全家桶", 
            "home_url": "Module_softether_vpn.asp", 
            "md5": "325ccc5fdd2024676c26dfec47057e00", 
            "name": "softether_vpn", 
            "tar_url": "softether_vpn/softether_vpn.tar.gz", 
            "title": "softether_vpn", 
            "version": "1.1.2"
        }, 
        {
            "build_date": "2017-10-16_14:51:31", 
            "changelog": "", 
            "description": "锐捷等802.1x认证客户端", 
            "home_url": "Module_minieap.asp", 
            "md5": "5e30958696b145b68aee1920e37fa55b", 
            "name": "minieap", 
            "tar_url": "minieap/minieap.tar.gz", 
            "title": "校园认证", 
            "version": "0.1"
        }, 
        {
            "build_date": "2020-01-03_15:50:29", 
            "changelog": "更新dnspod API", 
            "description": "动态域名解析工具", 
            "home_url": "Module_koolddns.asp", 
            "md5": "b01c12c5d4f174f155e7aa34f480f0bc", 
            "name": "koolddns", 
            "tar_url": "koolddns/koolddns.tar.gz", 
            "title": "Koolddns", 
            "version": "0.6.2"
        }, 
        {
            "build_date": "2019-02-25_21:35:18", 
            "changelog": "", 
            "description": "增强虚拟机操作系统性能", 
            "home_url": "Module_virtual.asp", 
            "md5": "b6564647ad0179b48debd483b2f2cfd2", 
            "name": "virtual", 
            "tar_url": "virtual/virtual.tar.gz", 
            "title": "虚拟机助手", 
            "version": "0.1"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/koolshare/koolshare.github.io/master", 
    "md5": "c963df648b30214aa0965f242091cc87", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "0.3.9"
}