{
    "apps": [
        {
            "build_date": "2017-12-11_18:06:02", 
            "changelog": "主程序更新到0.22", 
            "description": "外服游戏解决方案", 
            "home_url": "Module_sgame.asp", 
            "md5": "e7f9da96c19e3d6e97752cc146ea4d75", 
            "name": "sgame", 
            "tar_url": "sgame/sgame.tar.gz", 
            "title": "游戏加速器", 
            "version": "0.4"
        }, 
        {
            "build_date": "2017-10-12_15:16:43", 
            "changelog": "", 
            "description": "软件中心自动云备份和恢复", 
            "home_url": "Module_cos.asp", 
            "md5": "1af7f760d2a33089f2c543213ec8af8b", 
            "name": "cos", 
            "tar_url": "cos/cos.tar.gz", 
            "title": "腾讯云存储", 
            "version": "0.4"
        }, 
        {
            "build_date": "2017-10-02_22:27:11", 
            "changelog": "", 
            "description": "Godaddy-DDNS", 
            "home_url": "Module_gdddns.asp", 
            "md5": "a5305f32514fe3758638b703a19273e7", 
            "name": "gdddns", 
            "tar_url": "gdddns/gdddns.tar.gz", 
            "title": "gdddns", 
            "version": "1.3"
        }, 
        {
            "build_date": "2017-11-18_21:20:32", 
            "changelog": "修复自动生成配置文件的错误", 
            "description": "智能家庭网关", 
            "home_url": "Module_homebridge.asp", 
            "md5": "a132573a1e0d6dec55aee37d2f954549", 
            "name": "homebridge", 
            "tar_url": "homebridge/homebridge.tar.gz", 
            "title": "Homebridge", 
            "version": "0.6"
        }, 
        {
            "build_date": "2017-10-14_15:22:41", 
            "changelog": "", 
            "description": "仪表式查看路由详细状态", 
            "home_url": "Module_netdata.asp", 
            "md5": "3e5c0915964b29af4cd31cffe145c71a", 
            "name": "netdata", 
            "tar_url": "netdata/netdata.tar.gz", 
            "title": "路由监控", 
            "version": "0.1"
        }, 
        {
            "build_date": "2017-09-14_21:15:10", 
            "changelog": "修复重启酷软空白", 
            "description": "快速修复当前固件中的BUG", 
            "home_url": "Module_hotfix.asp", 
            "md5": "91cdf7c7ebea86dc73d50f8fa5c0b623", 
            "name": "hotfix", 
            "tar_url": "hotfix/hotfix.tar.gz", 
            "title": "HOTFIX", 
            "version": "0.2.0"
        }, 
        {
            "build_date": "2017-09-22_09:39:59", 
            "changelog": "", 
            "description": "VPN全家桶", 
            "home_url": "Module_softether_vpn.asp", 
            "md5": "f47152db7b9a32fc80884266ee17965c", 
            "name": "softether_vpn", 
            "tar_url": "softether_vpn/softether_vpn.tar.gz", 
            "title": "softether_vpn", 
            "version": "1.0.7"
        }, 
        {
            "build_date": "2017-11-24_18:16:42", 
            "changelog": "", 
            "description": "PPPOE服务器", 
            "home_url": "Module_pppoeserver.asp", 
            "md5": "b544bc87f2450e7de5cfcffb891c3f0b", 
            "name": "pppoeserver", 
            "tar_url": "pppoeserver/pppoeserver.tar.gz", 
            "title": "PPPoE Server", 
            "version": "0.1"
        }, 
        {
            "build_date": "2017-10-09_22:23:58", 
            "changelog": "", 
            "description": "增强路由NAT能力", 
            "home_url": "Module_sfe.asp", 
            "md5": "e2b8501f3b232ccd1a9ea0e83537d6a2", 
            "name": "sfe", 
            "tar_url": "sfe/sfe.tar.gz", 
            "title": "SFE快速转发引擎", 
            "version": "0.2"
        }, 
        {
            "build_date": "2017-11-21_21:49:06", 
            "changelog": "更新黑名单", 
            "description": "听说KP和软路由更搭哦~", 
            "home_url": "Module_koolproxy.asp", 
            "md5": "1a9b68e806df4b0b0ff0a22b7d880f25", 
            "name": "koolproxy", 
            "tar_url": "koolproxy/koolproxy.tar.gz", 
            "title": "koolproxy", 
            "version": "3.6.1.34"
        }, 
        {
            "build_date": "2017-10-03_00:51:16", 
            "changelog": "", 
            "description": "小巧便携BT下载器", 
            "home_url": "Module_cloud_torrent.asp", 
            "md5": "24e4769a0a69ad1d609cae1af1644077", 
            "name": "cloud_torrent", 
            "tar_url": "cloud_torrent/cloud_torrent.tar.gz", 
            "title": "cloud torrent", 
            "version": "1.6"
        }, 
        {
            "build_date": "2017-10-17_17:26:35", 
            "changelog": "", 
            "description": "宽带上下行提速", 
            "home_url": "Module_fastdick.asp", 
            "md5": "2f90f11ce9387bc7b74da7f409648272", 
            "name": "fastdick", 
            "tar_url": "fastdick/fastdick.tar.gz", 
            "title": "迅雷快鸟", 
            "version": "0.4"
        }, 
        {
            "build_date": "2017-10-16_19:22:00", 
            "changelog": "", 
            "description": "分布式的虚拟以太网", 
            "home_url": "Module_zerotier.asp", 
            "md5": "d97d8271a7da1cfd4ff813aae8d9b2b9", 
            "name": "zerotier", 
            "tar_url": "zerotier/zerotier.tar.gz", 
            "title": "ZeroTier", 
            "version": "0.1"
        }, 
        {
            "build_date": "2017-10-24_10:45:52", 
            "changelog": "√修复启动时导致插件锁定的BUG", 
            "description": "拨号到指定号段", 
            "home_url": "Module_pppoeai.asp", 
            "md5": "c518f2e044148006d147cbde20af7c4e", 
            "name": "pppoeai", 
            "tar_url": "pppoeai/pppoeai.tar.gz", 
            "title": "拨号助手", 
            "version": "0.9"
        }, 
        {
            "build_date": "2017-12-05_15:39:32", 
            "changelog": "更新主程序", 
            "description": "强大易用的全平台同步工具", 
            "home_url": "Module_easyexplorer.asp", 
            "md5": "2425d15496eca357e07a613e08aa952e", 
            "name": "easyexplorer", 
            "tar_url": "easyexplorer/easyexplorer.tar.gz", 
            "title": "EasyExplorer", 
            "version": "0.3"
        }, 
        {
            "build_date": "2017-09-29_18:06:01", 
            "changelog": "√修复重启导致防火墙规则重复", 
            "description": "巨硬套餐激活工具", 
            "home_url": "Module_kms.asp", 
            "md5": "206c88f07cc22e2013c3cc8df5883a68", 
            "name": "kms", 
            "tar_url": "kms/kms.tar.gz", 
            "title": "kms", 
            "version": "0.8"
        }, 
        {
            "build_date": "2017-11-12_17:56:59", 
            "changelog": "修复RPC密钥随机更改的问题", 
            "description": "超酷的远程下载工具", 
            "home_url": "Module_aria2.asp", 
            "md5": "ec0c4595a3c90531f29d259aeb785bf8", 
            "name": "aria2", 
            "tar_url": "aria2/aria2.tar.gz", 
            "title": "Aria2", 
            "version": "1.9"
        }, 
        {
            "build_date": "2017-10-13_10:50:08", 
            "changelog": "", 
            "description": "Debian系统和Unifi控制器", 
            "home_url": "Module_unifi.asp", 
            "md5": "815f9c6c7aad452a4a24f6686b2bef3c", 
            "name": "unifi", 
            "tar_url": "unifi/unifi.tar.gz", 
            "title": "Unifi Controller", 
            "version": "0.3"
        }, 
        {
            "build_date": "2017-10-19_16:08:11", 
            "changelog": "修复新固件下客户端上线通知失效", 
            "description": "推送路由器信息到微信~", 
            "home_url": "Module_serverchan.asp", 
            "md5": "3d0636c351498feb0a0e31cef780bcff", 
            "name": "serverchan", 
            "tar_url": "serverchan/serverchan.tar.gz", 
            "title": "Server酱", 
            "version": "1.1.6"
        }, 
        {
            "build_date": "2017-11-27_13:01:43", 
            "changelog": "", 
            "description": "在线更新路由器固件", 
            "home_url": "Module_fwupdate.asp", 
            "md5": "52b269e1409c4aef9204e605630d058b", 
            "name": "fwupdate", 
            "tar_url": "fwupdate/fwupdate.tar.gz", 
            "title": "固件更新", 
            "version": "0.2.6"
        }, 
        {
            "build_date": "2017-09-09_18:23:16", 
            "description": "将客户端完全暴露在公网", 
            "home_url": "Module_dmz.asp", 
            "md5": "a428eb4ab6054972cfa01d0e34ab5507", 
            "name": "dmz", 
            "tar_url": "dmz/dmz.tar.gz", 
            "title": "DMZ", 
            "version": "0.4"
        }, 
        {
            "build_date": "2017-09-13_21:32:02", 
            "changelog": "↑ 更新二进制文件", 
            "description": "UDP双边加速工具", 
            "home_url": "Module_udpspeeder.asp", 
            "md5": "85a543b8e36af5de86b01c0f8ed3aec5", 
            "name": "udpspeeder", 
            "tar_url": "udpspeeder/udpspeeder.tar.gz", 
            "title": "UDPspeeder", 
            "version": "1.0.6"
        }, 
        {
            "build_date": "2017-10-19_20:43:20", 
            "changelog": "", 
            "description": "安装盘剩余空间挂载", 
            "home_url": "Module_kdisk.asp", 
            "md5": "4a48bfb02f098af70635df78df6004de", 
            "name": "kdisk", 
            "tar_url": "kdisk/kdisk.tar.gz", 
            "title": "硬盘助手", 
            "version": "0.2"
        }, 
        {
            "build_date": "2017-09-09_18:25:45", 
            "description": "DNSPOD动态域名解析", 
            "home_url": "Module_dnspod.asp", 
            "md5": "97477066986e4c8ad94f10129eed8881", 
            "name": "dnspod", 
            "tar_url": "dnspod/dnspod.tar.gz", 
            "title": "dnspod", 
            "version": "1.4"
        }, 
        {
            "build_date": "2017-12-09_01:02:22", 
            "changelog": "1.9.9.7", 
            "description": "轻松科学上网~", 
            "home_url": "Module_koolss.asp", 
            "md5": "0d79064503b56ebbd3d78db35201498f", 
            "name": "koolss", 
            "tar_url": "koolss/koolss.tar.gz", 
            "title": "科学上网插件", 
            "version": "1.9.9.7"
        }, 
        {
            "build_date": "2017-09-09_18:25:54", 
            "description": "FRPC内网穿透工具", 
            "home_url": "Module_frpc.asp", 
            "md5": "a812e495d98bb22a7dc119dbb6e2ac68", 
            "name": "frpc", 
            "tar_url": "frpc/frpc.tar.gz", 
            "title": "frpc", 
            "version": "1.6"
        }, 
        {
            "build_date": "2017-08-07_23:30:31", 
            "description": "超强的SSH网页客户端", 
            "home_url": "Module_shellinabox.asp", 
            "md5": "030789c4f28c34bafa3a65f16198691b", 
            "name": "shellinabox", 
            "tar_url": "shellinabox/shellinabox.tar.gz", 
            "title": "ShellnaBox", 
            "version": "1.1.5"
        }, 
        {
            "name": "nwan", 
            "tar_url": "nwan/nwan.tar.gz", 
            "title": "nwan"
        }, 
        {
            "build_date": "2017-12-03_16:10:38", 
            "changelog": "增加SSL源进源出选项", 
            "description": "多运营商自动分流", 
            "home_url": "Module_policy.asp", 
            "md5": "feb538760dd7b895a0fed5fad1765cde", 
            "name": "policy", 
            "tar_url": "policy/policy.tar.gz", 
            "title": "策略路由", 
            "version": "0.3"
        }, 
        {
            "build_date": "2017-11-11_15:56:45", 
            "changelog": "√修复全局连接数无法修改的问题", 
            "description": "高效的BT、PT下载工具", 
            "home_url": "Module_transmission.asp", 
            "md5": "a3ff4cd0ed9af1c68e05f9274dcc47d0", 
            "name": "transmission", 
            "tar_url": "transmission/transmission.tar.gz", 
            "title": "Transmission", 
            "version": "0.4"
        }, 
        {
            "build_date": "2017-09-09_18:30:46", 
            "description": "上下行带宽提速", 
            "home_url": "Module_kuainiao.asp", 
            "md5": "130068e43c0185e2b578b7dc69561e72", 
            "name": "kuainiao", 
            "tar_url": "kuainiao/kuainiao.tar.gz", 
            "title": "kuainiao", 
            "version": "1.1"
        }, 
        {
            "build_date": "2017-10-01_16:30:07", 
            "changelog": "", 
            "description": "内存管理小助手", 
            "home_url": "Module_memory.asp", 
            "md5": "5c32304458a48423e79d042cdef50c84", 
            "name": "memory", 
            "tar_url": "memory/memory.tar.gz", 
            "title": "内存管理", 
            "version": "0.2"
        }, 
        {
            "build_date": "2017-09-09_18:21:59", 
            "description": "阿里云解析自动更新IP", 
            "home_url": "Module_aliddns.asp", 
            "md5": "e980e0c85dd809ba3f831744d08c628d", 
            "name": "aliddns", 
            "tar_url": "aliddns/aliddns.tar.gz", 
            "title": "AliDDNS", 
            "version": "0.7"
        }, 
        {
            "build_date": "2017-08-31_14:34:01", 
            "description": "将USB磁盘自动挂载到系统", 
            "home_url": "Module_usbmount.asp", 
            "md5": "1b653aa56517aa80bd394e91ad754e84", 
            "name": "usbmount", 
            "tar_url": "usbmount/usbmount.tar.gz", 
            "title": "USB自动挂载", 
            "version": "1.0"
        }, 
        {
            "build_date": "2017-11-16_00:17:13", 
            "changelog": "", 
            "description": "科学上网服务器", 
            "home_url": "Module_ssrserver.asp", 
            "md5": "de375fbf147d7ccdde38bd9aa4c646ba", 
            "name": "ssrserver", 
            "tar_url": "ssrserver/ssrserver.tar.gz", 
            "title": "SSR Server", 
            "version": "0.1"
        }, 
        {
            "build_date": "2017-10-25_10:49:24", 
            "changelog": "√修复重启防火墙规则可能丢失的BUG", 
            "description": "高安全的企业VPN服务器", 
            "home_url": "Module_ikev1.asp", 
            "md5": "b94276026e7bb06b14729997be280a48", 
            "name": "ikev1", 
            "tar_url": "ikev1/ikev1.tar.gz", 
            "title": "IPsec服务器", 
            "version": "0.9"
        }, 
        {
            "build_date": "2017-09-09_18:28:12", 
            "description": "小宝开发的游戏加速V2", 
            "home_url": "Module_koolgame.asp", 
            "md5": "d01e0878e17f27934645d8c2484b1e9a", 
            "name": "koolgame", 
            "tar_url": "koolgame/koolgame.tar.gz", 
            "title": "游戏加速", 
            "version": "1.0.2"
        }, 
        {
            "build_date": "2017-09-19_12:21:44", 
            "changelog": "", 
            "description": "使PPPoE能够跨路由使用", 
            "home_url": "Module_pppoerelay.asp", 
            "md5": "22ba1771273ee9b3248ad73968d5e710", 
            "name": "pppoerelay", 
            "tar_url": "pppoerelay/pppoerelay.tar.gz", 
            "title": "PPPoE Relay", 
            "version": "0.1"
        }, 
        {
            "build_date": "2017-10-03_00:53:49", 
            "changelog": "", 
            "description": "轻松搭建私有云", 
            "home_url": "Module_syncthing.asp", 
            "md5": "933176300150bc2926ba00daf6299b61", 
            "name": "syncthing", 
            "tar_url": "syncthing/syncthing.tar.gz", 
            "title": "syncthing", 
            "version": "1.8"
        }, 
        {
            "build_date": "2017-11-26_00:00:19", 
            "changelog": "修复2.9无法使用证书登陆", 
            "description": "与你的网络无缝并行", 
            "home_url": "Module_anyconnect.asp", 
            "md5": "82f064de30f90ad7163a272e9f1b9664", 
            "name": "anyconnect", 
            "tar_url": "anyconnect/anyconnect.tar.gz", 
            "title": "AnyConnect Server", 
            "version": "0.5"
        }, 
        {
            "build_date": "2017-10-12_11:01:40", 
            "changelog": "", 
            "description": "自动化部署WEB环境", 
            "home_url": "Module_lnmp.asp", 
            "md5": "c11f11e5c7389d64b0a445149d79ce60", 
            "name": "lnmp", 
            "tar_url": "lnmp/lnmp.tar.gz", 
            "title": "LNMP", 
            "version": "0.6"
        }, 
        {
            "build_date": "2017-10-16_14:51:31", 
            "changelog": "", 
            "description": "锐捷等802.1x认证客户端", 
            "home_url": "Module_minieap.asp", 
            "md5": "5e30958696b145b68aee1920e37fa55b", 
            "name": "minieap", 
            "tar_url": "minieap/minieap.tar.gz", 
            "title": "校园认证", 
            "version": "0.1"
        }, 
        {
            "build_date": "2017-09-10_23:08:06", 
            "description": "应对udp限速、屏蔽", 
            "home_url": "Module_udp2raw.asp", 
            "md5": "78cb38c360fa9a45cd16d820609d22f8", 
            "name": "udp2raw", 
            "tar_url": "udp2raw/udp2raw.tar.gz", 
            "title": "udp2raw", 
            "version": "0.3"
        }, 
        {
            "build_date": "2017-11-02_22:40:01", 
            "changelog": "", 
            "description": "自动部署SSL证书", 
            "home_url": "Module_acme.asp", 
            "md5": "3fb0f1f841ba9a3c883ea3deb61393eb", 
            "name": "acme", 
            "tar_url": "acme/acme.tar.gz", 
            "title": "Let's Encrypt", 
            "version": "0.1"
        }, 
        {
            "build_date": "2017-10-18_11:08:01", 
            "changelog": "", 
            "description": "修复迅雷不能下载的BUG", 
            "home_url": "Module_xldoc.asp", 
            "md5": "f364044d13f0917398079b05e472f90a", 
            "name": "xldoc", 
            "tar_url": "xldoc/xldoc.tar.gz", 
            "title": "救救迅雷", 
            "version": "0.2"
        }, 
        {
            "build_date": "2017-10-12_11:02:55", 
            "changelog": "", 
            "description": "稳定高效的共享磁盘", 
            "home_url": "Module_iscsi.asp", 
            "md5": "bce7398c37f6797ca4fcf6c874490df6", 
            "name": "iscsi", 
            "tar_url": "iscsi/iscsi.tar.gz", 
            "title": "iSCSI服务器", 
            "version": "0.5"
        }, 
        {
            "build_date": "2017-10-12_15:18:30", 
            "changelog": "", 
            "description": "小巧安全的FTP服务器", 
            "home_url": "Module_ftp.asp", 
            "md5": "4dcc993dd617ed88a3db1938aad0aa06", 
            "name": "ftp", 
            "tar_url": "ftp/ftp.tar.gz", 
            "title": "FTP服务器", 
            "version": "1.0.4"
        }, 
        {
            "build_date": "2017-09-11_23:49:21", 
            "description": "支持http2协议的远程管理，仅支持远程管理路由器+NAS+Windows远程桌面", 
            "home_url": "Module_ddnsto.asp", 
            "md5": "81cdb6b8185cf9ee08dcca835069e07d", 
            "name": "ddnsto", 
            "tar_url": "ddnsto/ddnsto.tar.gz", 
            "title": "DDNSTO", 
            "version": "1.8"
        }
    ], 
    "home_url": "https://raw.githubusercontent.com/koolshare/koolshare.github.io/master", 
    "md5": "dbbd6f85ef0aad24e3c3d56bc7cd5a36", 
    "tar_url": "softcenter/softcenter.tar.gz", 
    "version": "0.3.1"
}